<?xml version='1.0'?>
<sdf version='1.7' xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="RollingRobot" params="suffix:='' parent_link:='' x:=0 y:=0 z:=0 roll:=0 pitch:=0 yaw:=0 rotation_offset:=0">
        <xacro:if value="${suffix == ''}">
            <xacro:property name="model_name" value="RollingRobot" />
        </xacro:if>
        <xacro:unless value="${suffix == ''}">
            <xacro:property name="model_name" value="RollingRobot_${suffix}" />
        </xacro:unless>

        <xacro:property name="weight_z_offset" value="-0.025" />

        <link name='${model_name}_Ball'>
            <inertial>
                <mass>0.25</mass>
                <inertia>
                    <ixx>0.00035345</ixx>
                    <ixy>0</ixy>
                    <ixz>0</ixz>
                    <iyy>0.00035345</iyy>
                    <iyz>0</iyz>
                    <izz>0.00035345</izz>
                </inertia>
                <pose>0 0 0 0 -0 0</pose>
            </inertial>
            <pose>${x} ${y} ${z} ${roll} ${pitch} ${yaw}</pose>
            <gravity>1</gravity>
            <self_collide>0</self_collide>
            <kinematic>0</kinematic>
            <enable_wind>0</enable_wind>
            <visual name='visual'>
                <pose>0 0 0 0 -0 0</pose>
                <geometry>
                    <mesh>
                        <uri>$(find robot_simulation)/models/RollingRobot/Ball.dae</uri>
                        <scale>1 1 1</scale>
                    </mesh>
                </geometry>
                <transparency>0</transparency>
                <cast_shadows>1</cast_shadows>
            </visual>
            <collision name='collision'>
                <laser_retro>0</laser_retro>
                <max_contacts>10</max_contacts>
                <pose>0 0 0 0 -0 0</pose>
                <geometry>
                    <sphere>
                        <radius>0.05</radius>
                    </sphere>
                </geometry>
                <surface>
                    <contact>
                        <collide_bitmask>65535</collide_bitmask>
                        <ode>
                            <min_depth>0.001</min_depth>
                            <kp>1e15</kp>
                            <kd>1e13</kd>
                        </ode>
                    </contact>
                    <friction>
                        <ode>
                            <mu>100</mu>
                            <mu2>100</mu2>
                        </ode>
                        <torsional>
                            <ode/>
                        </torsional>
                    </friction>
                    <bounce/>
                </surface>
            </collision>
        </link>

        <link name='${model_name}_Rod'>
            <inertial>
                <mass>0.01</mass>
                <inertia>
                    <ixx>0.0000035345</ixx>
                    <ixy>0</ixy>
                    <ixz>0</ixz>
                    <iyy>0.000035345</iyy>
                    <iyz>0</iyz>
                    <izz>0.000035345</izz>
                </inertia>
                <pose>0 0 0 0 -0 0</pose>
            </inertial>
            <pose>${x} ${y} ${z} ${roll} ${pitch} ${yaw}</pose>
            <gravity>1</gravity>
            <self_collide>0</self_collide>
            <kinematic>0</kinematic>
            <enable_wind>0</enable_wind>
            <visual name='visual'>
                <pose>0 0 0 0 -0 0</pose>
                <geometry>
                    <box>
                        <size>0.01 0.05 0.01</size>
                    </box>
                </geometry>
                <transparency>0</transparency>
                <cast_shadows>1</cast_shadows>
            </visual>
        </link>

        <link name='${model_name}_Weight'>
            <inertial>
                <mass>0.3605447</mass>
                <inertia>
                    <ixx>0.00005013</ixx>
                    <ixy>0</ixy>
                    <ixz>0</ixz>
                    <iyy>0.00010328</iyy>
                    <iyz>0</iyz>
                    <izz>0.00008874</izz>
                </inertia>
                <pose>0 0 0 0 1.5708</pose>
            </inertial>
            <pose>${x} ${y} ${z + weight_z_offset} ${roll} ${pitch} ${yaw}</pose>
            <gravity>1</gravity>
            <self_collide>0</self_collide>
            <kinematic>0</kinematic>
            <enable_wind>0</enable_wind>
            <visual name='visual'>
                <pose>0 0 0 0 -0  1.5708</pose>
                <geometry>
                    <mesh>
                        <uri>$(find robot_simulation)/models/RollingRobot/Weight.dae</uri>
                        <scale>1 1 1</scale>
                    </mesh>
                </geometry>
                <transparency>0</transparency>
                <cast_shadows>1</cast_shadows>
            </visual>
        </link>

        <joint name='${model_name}_ball_weight_advance_joint' type='revolute'>
            <parent>${model_name}_Ball</parent>
            <child>${model_name}_Rod</child>
            <pose>0 0 0 0 -0 0</pose>
            <axis>
                <xyz>0 1 0</xyz>
                <limit>
                    <lower>-1.79769e+308</lower>
                    <upper>1.79769e+308</upper>
                    <effort>-1</effort>
                    <velocity>-1</velocity>
                </limit>
                <dynamics>
                    <damping>0.0001</damping>
                    <friction>0.0001</friction>
                </dynamics>
            </axis>
            <physics>
                <ode>
                    <limit>
                        <cfm>0</cfm>
                        <erp>0.8</erp>
                    </limit>
                </ode>
            </physics>
        </joint>

        <joint name='${model_name}_ball_weight_turn_joint' type='revolute'>
            <parent>${model_name}_Rod</parent>
            <child>${model_name}_Weight</child>
            <pose>0 0 ${-weight_z_offset} 0 -0 0</pose>
            <axis>
                <xyz>1 0 0</xyz>
                <limit>
                    <lower>-0.5</lower>
                    <upper>0.5</upper>
                    <effort>-1</effort>
                    <velocity>-1</velocity>
                </limit>
                <dynamics>
                    <damping>0.01</damping>
                    <friction>0.001</friction>
                </dynamics>
            </axis>
            <physics>
                <ode>
                    <limit>
                        <cfm>0</cfm>
                        <erp>0.8</erp>
                    </limit>
                </ode>
            </physics>
        </joint>

<!--        <joint name='${model_name}_ball_weight_turn_joint' type='revolute'>-->
<!--            <parent>${model_name}_Ball</parent>-->
<!--            <child>${model_name}_Weight</child>-->
<!--            <pose>0 0 ${-weight_z_offset} 0 -0 0</pose>-->
<!--            <axis>-->
<!--                <xyz>1 0 0</xyz>-->
<!--                <limit>-->
<!--                    <lower>-1.79769e+308</lower>-->
<!--                    <upper>1.79769e+308</upper>-->
<!--                    <effort>-1</effort>-->
<!--                    <velocity>-1</velocity>-->
<!--                </limit>-->
<!--                <dynamics>-->
<!--                    <damping>0.001</damping>-->
<!--                    <friction>0.001</friction>-->
<!--                </dynamics>-->
<!--            </axis>-->
<!--            <physics>-->
<!--                <ode>-->
<!--                    <limit>-->
<!--                        <cfm>0</cfm>-->
<!--                        <erp>0.8</erp>-->
<!--                    </limit>-->
<!--                </ode>-->
<!--            </physics>-->
<!--        </joint>-->


    </xacro:macro>
</sdf>